# Generated by Django 5.0.6 on 2024-06-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPTK', '0002_alter_userptk_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userptk',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userptk',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
    ]
