# Generated by Django 5.0.6 on 2024-06-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('EPO', 'Epoxy'), ('TAP', 'Tape'), ('PUT', 'Putty'), ('SIL', 'Silicone'), ('CYA', 'Cyanoacrylate'), ('GLU', 'Glue PVC/CPVC')], default='EPO', max_length=3),
        ),
    ]
