# Generated by Django 5.0.6 on 2024-06-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_rotation_user_rotation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rotation',
            old_name='user',
            new_name='users',
        ),
    ]
