# Generated by Django 5.0.6 on 2024-06-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_remove_rotation_users_rotation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinrotation',
            name='product',
            field=models.SmallIntegerField(default=1),
        ),
    ]
