# Generated by Django 5.0.6 on 2024-06-28 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_productinrotation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinrotation',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
    ]
